config/routes.rb
Rails.application.routes.draw do

  root 'linkedins#home'
  get '/welcome' => 'linkedins#index', as: :generate
  get '/accept' => 'linkedins#accept'

  resources :users, :resovisions, :positions, :educations

  # Sessions
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy', as: :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>ResovisionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="//assets.ziggeo.com/css/ziggeo-betajs-player.min.css" />
  <script src="//assets.ziggeo.com/js/ziggeo-json2-betajs-player.min.js"></script>
  <script>ZiggeoApi.token = "1a96227f1aca8f46d85f7a270b8e8266";</script>

  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>

</head>
<body>
<div class="container">
  <% if current_user %>
  <header>
    <% if current_user %>
      <div id=left-nav>
        <nav>
          <span> Welcome, <%= current_user.resovision.first_name %></span>
          <a><%= link_to 'Log Out', logout_path %></a>
        </nav>
      </div>
    <div id="right-nav">
      <nav>
        <a><%= link_to 'Home', root_path %> | </a>
        <a><%= link_to 'Public Resovision', resovision_path(current_user.resovision) %> | </a>
        <a><%= link_to 'Edit Your Resovision', edit_resovision_path(current_user.resovision) %> |</a>
        <a><%= link_to 'Account Settings', user_path(current_user) %> </a>
      </nav>
    </div>
    <% end %>
  </header>
  <% end %>

  <%= yield %>
</div>
</body>
</html>